import Head from "next/head"
import Image from "next/image"
import { gql } from "@apollo/client"
import client from "../utils/apolloClient"
import styles from "../styles/Home.module.css"
import ClientOnly from "../utils/ClientOnly"
import Posts from "./posts"

export default function Home({ site }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>{site.title || "Site Name"}</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>{site.url}</main>
		</div>
	)
}
export async function getStaticProps() {
	const { data } = await client.query({
		query: gql`
			query Site {
				generalSettings {
					url
					title
				}
			}
		`,
	})

	return {
		props: {
			site: data.generalSettings,
		},
	}
}
